BEGIN;

-- If the legacy customer table is still named "user", rename it first.
DO $$
BEGIN
  IF to_regclass('public.customers') IS NULL AND to_regclass('public."user"') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public."user" RENAME TO customers';
  END IF;
END $$;

-- Stop early if there is still no customer table to migrate.
DO $$
BEGIN
  IF to_regclass('public.customers') IS NULL THEN
    RAISE EXCEPTION 'No existe la tabla public.customers ni public."user".';
  END IF;
END $$;

-- Keep a full backup before restructuring.
DROP TABLE IF EXISTS customers_legacy_backup;
CREATE TABLE customers_legacy_backup AS TABLE customers;

-- Rebuild the table with only id and phone.
DROP TABLE IF EXISTS customers_new;
CREATE TABLE customers_new (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone VARCHAR(50) NOT NULL UNIQUE
);

-- Normalize phones, discard empty phones, and keep only the first row for duplicates.
WITH normalized AS (
  SELECT
    id,
    NULLIF(regexp_replace(COALESCE(phone, ''), '[^0-9+]', '', 'g'), '') AS clean_phone,
    ROW_NUMBER() OVER (
      PARTITION BY NULLIF(regexp_replace(COALESCE(phone, ''), '[^0-9+]', '', 'g'), '')
      ORDER BY id
    ) AS duplicate_rank
  FROM customers
)
INSERT INTO customers_new (id, phone)
SELECT id, clean_phone
FROM normalized
WHERE clean_phone IS NOT NULL
  AND duplicate_rank = 1
ORDER BY id;

DROP TABLE customers;
ALTER TABLE customers_new RENAME TO customers;

CREATE UNIQUE INDEX idx_customers_phone ON customers(phone);

SELECT setval(
  pg_get_serial_sequence('customers', 'id'),
  COALESCE((SELECT MAX(id) FROM customers), 1),
  true
);

COMMIT;
